export const GETSTARTED = 'Get Started';
export const SIGNIN = 'Sign In';
export const WATCHLIST = 'Watch List';
export const ADDWATCHLISTITEM = 'Add Watch List Item';
export const BOTTOMTAB = 'Bottom Tab';
export const HOME = 'Home';
export const NEWHOT = 'New & Hot';
export const SEARCH = 'Search';
export const DOWNLOAD = 'Download';
